services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    volumes:
      - /home/scallanan/work/caddy/etc/caddy:/etc/caddy
      - /home/scallanan/work/caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    network_mode: "host"

volumes:
  caddy_data:
  caddy_config:

