services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ${PWD}/etc/caddy:/etc/caddy
      - ${PWD}/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    network_mode: "host"

volumes:
  caddy_data:
  caddy_config:

